name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.1
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: curl -L https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }} > source.tar.gz
      - uses: ./
        with:
          source: source.tar.gz
          w3up-private-key: ${{ secrets.W3UP_PRIVATE_KEY }}
          w3up-proof: ${{ secrets.W3UP_PROOF }}
          w3name-private-key: ${{ secrets.W3NAME_PRIVATE_KEY }}
          w3name-revision: ${{ secrets.W3NAME_REVISION }}
